# nsd
Nassi-Shneiderman-Diagramme (NSD) Programmstrukture werden auch als Struktogramme bezeichnet.


Das Repository enthält verschiedene Zweige, die Struktogramme enthalten,
die über das Programm _Struktorizer_ ( https://structorizer.fisch.lu/ ) 
erstellt wurden


Jeder Zweig beginnt mit einem Benutzernamen,  `<user>`. 
Der restliche gibt Hinweise auf die umgesetzte Aufgabenstellung.

----
<user>/bws/lf6/cpp-basics/Programmverzweigungen/A05-Zeugnis-Versetzung
<user>/ihk/2017/WJ/A11-Getränkeahandlung
----

Dieses remote Repository hat den URL: https://github.com/msg-azubi/nsd.git

Um ein lokales Repository mit diesem remote Repository zu verbinden,
sind folgende Schritte nötig:

* In das Wurzelverzeichnis (_engl._ root directory) des lokalen Repository wechseln
+
.Per Git-Bash
----
cd /c/dev/azubis/structorizer-projects
----

* Dem lokalen Repository sagen, das der remote Repository name `origin` auf einen bestimmte URL zu zeigen hat:
+
.Den URL des remote Repository den remote Schlüssek (_engl._ key) `origin` zuordnen.
----
git remote add origin https://github.com/msg-azubi/nsd.git
----

